version: "3.9"

services:
  tfserve:
    image: tensorflow/serving
    ports: 
      - 8501:8501
    environment:
      MODEL_NAME: dog_model
    volumes:
      - ./models/dog_model:/models/dog_model
    depends_on: 
      - streamlit
  
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
      args:
        CONFIG: TENSORFLOW
    image: streamlit:minikube
    ports:
      - 8502:8502
    volumes:
      - ./models:/app/models

  seldon:
    build: 
      context: .
      dockerfile: Dockerfile.seldon
    ports: 
      - "9000:9000"
    depends_on: 
      - streamlit
 
    
#  environment:
#       - SELDON
#       - TFSERVE