FROM python:3.8

RUN mkdir /models

WORKDIR /app
COPY requirements.txt requirements.txt 
RUN pip install -r requirements.txt 

COPY ./train_model.py .
#COPY ./models ./models


EXPOSE 5000

CMD [ "python3" , "train_model.py" ]

