version: "3.9"

services:
  tfserve:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - ./dog_model:/models/dog_model
    environment:
      MODEL_NAME: dog_model

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8502:8502
    volumes:
      - ./labels:/dog_model
