version: "3.9"

services:
  seldon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - streamlit-seldon
    volumes:
      - ./models:/models

  streamlit-seldon:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
      args:
        CONFIG: SELDON
        ENV: COMPOSE
    image: streamlit:minikube
    ports:
      - 8502:8502
    volumes:
      - ./models:/app/models