FROM python:3.8

EXPOSE 8501

WORKDIR /app

COPY constraint.txt constraint.txt
RUN pip install streamlit==1.11.1 -c constraint.txt

RUN pip3 install tensorflow==2.9.1 seldon-core==1.14.0 scipy==1.9.0

COPY app.py app.py
COPY ./savedimage ./savedimage
#COPY ./models ./models     

CMD streamlit run app.py