FROM python:3.8

EXPOSE 8502

WORKDIR /app

RUN mkdir -p /app/labels
COPY requirements-streamlit.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py app.py
COPY ./savedimage ./savedimage

CMD streamlit run app.py --server.port 8502