FROM python:3.8

RUN mkdir /models

WORKDIR /app

ARG  CONFIG
ENV CONFIG ${CONFIG}

RUN pip install --upgrade pip

COPY requirements.txt requirements.txt 
RUN pip install -r requirements.txt 

COPY ./train_model.py .

EXPOSE 5000

CMD [ "python3" , "train_model.py" ]