apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: dog-breed
spec:
  name: dog-breed-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: dog-breed
          image: dog-breed:minikube
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    annotations:
      predictor_version: "0.1"
      seldon.io/svc-name: dog-breed-svc    
    name: my-graph
    replicas: 1