apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-dogbreed
  namespace: seldon
spec:
  name: seldon-dogbreed
  predictors:
    - name: seldon-dogbreed
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - image: dogbreed:minikube
                imagePullPolicy: IfNotPresent
                name: seldon-dogbreed
                env:
                  - name: CONFIG
                    value: "SELDON"
                  - name: ENV
                    value: "KUBERNETES"
                volumeMounts:
                  - name: models
                    mountPath: /models
            volumes:
              - name: models
                hostPath:
                  path: /mnt
      graph:
        children: []
        endpoint:
          type: REST
        name: seldon-dogbreed
        type: MODEL