apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: app
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 8502
      targetPort: streamlit-svc