apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: dogbreed-seldon
  namespace: seldon
spec:
  name: dogbreed-seldon
  predictors:
    - name: dogbreed
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - image: dogbreed:minikube
                imagePullPolicy: IfNotPresent
                name: dogbreed
      graph:
        children: []
        endpoint:
          type: REST
        name: dogbreed
        type: MODEL