apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: kubeflow-mapping
spec:
  hostname: "*"
  prefix: /kubeflow/
  rewrite: /
  use_websocket: true
  service: ml-pipeline-ui.kubeflow:80