apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: streamlit:minikube
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG
              value: "TENSORFLOW"
            - name: ENV
              value: "KUBERNETES"
          ports:
            - name: streamlit-svc
              containerPort: 8502
          volumeMounts:
            - name: labels
              mountPath: /app/models
      volumes: 
        - name: labels
          hostPath:
            path: /mnt

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: app
spec:
  selector:
    app: streamlit
  ports:
    - name: http
      port: 8502
      targetPort: streamlit-svc


    
